pileup:
  qual_min: 15
  clip_minL: 100
plots:
  coverage-maxbins: 2500
  gaps:
    n-top-trajs: 33
    freq-threshold: 0.75
    coverage-threshold: 5
  consensus:
    n-top-trajs: 33
    freq-threshold: 0.75
    coverage-threshold: 5
  insertions:
    n-top-trajs: 33
    freq-threshold: 0.5
    coverage-threshold: 5
    coverage-window: 100
    coverage-fraction: 0.5
  clips:
    n-top-trajs: 33
    freq-threshold: 0.75
    coverage-threshold: 5
    coverage-window: 100
    coverage-fraction: 0.1
  supplementary:
    length-threshold: 50
  secondary:
    length-threshold: 50